import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import type { FlowResult } from './types.js';

const DEFAULT_RESULT = path.resolve('output/contact-from-home/flow-result.json');

function formatStepDescription(description: string): string {
  return description
    .trim()
    .split('\n')
    .map((line) => line.trim())
    .join(' ');
}

function renderMarkdown(result: FlowResult): string {
  const { flow, recorded_at, steps } = result;
  const lines: string[] = [
    `# ${flow.title}`,
    '',
    flow.description.trim(),
    '',
    `> **Site:** [${flow.site}](${flow.site})`,
    `> **Generated:** ${recorded_at}`,
  ];

  steps.forEach((step, index) => {
    lines.push('', `## Step ${index + 1}. ${step.title}`, '');
    lines.push(formatStepDescription(step.description));
    if (step.screenshot) {
      lines.push('', `![${step.title}](${step.screenshot})`);
    }
    lines.push('', `<small>URL at this step: ${step.url}</small>`);
  });

  lines.push('', '---', '', '*Generated by demo-as-code flow recorder.*');
  return lines.join('\n');
}

export async function generateGuide(resultPath = DEFAULT_RESULT): Promise<string> {
  const content = await readFile(resultPath, 'utf8');
  const result = JSON.parse(content) as FlowResult;
  const markdown = renderMarkdown(result);
  const outputPath = path.join(path.dirname(resultPath), 'guide.md');
  await writeFile(outputPath, markdown, 'utf8');
  console.log(`Guide written → ${outputPath}`);
  return outputPath;
}

const resultArg = process.argv[2];
generateGuide(resultArg).catch((error) => {
  console.error(error);
  process.exit(1);
});
